=== bruceblack88/JavaPlayground/Derby/db-derby-10.15.2.0-src/db-derby-10.15.2.0-src/java/org.apache.derby.engine/org/apache/derby/security/securityPolicies.dtd
<?xml version="1.0" encoding="utf-8"?>

<!-- 
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at      

http://www.apache.org/licenses/LICENSE-2.0  

Unless required by applicable law or agreed to in writing, software  
distributed under the License is distributed on an "AS IS" BASIS,  
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
See the License for the specific language governing permissions and  
limitations under the License.
-->

<!-- 
This is the grammar which defines the structure of securityPolicies.xml.
That file, in turn, is the source code used to generate security policies
for the following purposes:

 * production usage
 * testing
 * pages in the Derby Security Guide

Elements of the grammar have the following meanings:

 * policies - Root element.
 * policy - Describes a policy file.
 * name - Internal handle, referenced by <include> elements
 * include - (Optional) Other policies to include
 * output - (Optional) Name of file to generate; properties for customizing the grant targets
 * block - A block of permissions to add or delete
 * comment - (Optional) comment to place before the permission block
 * a - Permission to add
 * d - Permission to delete

This grammar supports the following concepts:

o Policy - A policy is a list of jars with an optional
           set of instructions for how to format and output the
           policy. A policy may include other policies.
           At a high level, a policy may be viewed as a set of deltas
           from the parent policies which it includes.

o Jar    - A jar is a grant target. It is a list of permission blocks.
           The target is specified as a logical name which the output
           descriptor later maps to a physical jar file name.

o Block  - A permission block is a (possibly commented) list of
           privileges, which are granted to the enclosing jar.
           Permissions may be added. They may also be deleted
           from corresponding permission blocks included
           by the enclosing policy.

o Output - An output descriptor specifies the file to which the policy
           is written. By default, the file will be formatted as a
           valid Java security policy. However, the descriptor may
           specify that the output should be formatted as DITA source
           XML, for inclusion in the Derby Security Guide.
           An output descriptor references a set of properties
           which are used to map logical jar file names to actual,
           physical files located in the local file system.
-->

<!ELEMENT policies (policy+)>
<!ELEMENT policy (name, include*, output?, jar*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT include (#PCDATA)>
<!ELEMENT output (file, properties, doc?)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT properties (#PCDATA)>
<!ELEMENT doc (title, shortDesc, majorIndexTerm, minorIndexTerm, longDesc)>
<!ELEMENT jar (name, block+)>
<!ELEMENT block (comment?, a*, d*)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT a (#PCDATA)>
<!ELEMENT d (#PCDATA)>

=== bruceblack88/JavaPlayground/Derby/db-derby-10.15.2.0-src/db-derby-10.15.2.0-src/java/org.apache.derby.engine/org/apache/derby/security/securityPolicies.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "securityPolicies.dtd">

<!-- 
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at      

http://www.apache.org/licenses/LICENSE-2.0  

Unless required by applicable law or agreed to in writing, software  
distributed under the License is distributed on an "AS IS" BASIS,  
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  
See the License for the specific language governing permissions and  
limitations under the License.
--> 


<!-- 
This file contains all of the permissions used by Derby policy files.

For a description of the XML grammar used here, see securityPolicy.dtd.
-->

<policies>

  <!--
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     !!
     !! Production policies.
     !!
     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  -->

  <!-- org.apache.derby.commons -->

  <policy>
    <name>basicCommons</name>

    <jar>
      <name>derbyshared.jar</name>

      <block>
        <comment>Needed to determine whether the JVM was booted with a module path.</comment>
        <a>java.util.PropertyPermission "jdk.module.path", "read"</a>
      </block>

      <block>
        <comment>Need in order to read message localizations from other derby jars
when running with a module path.</comment>
        <a>java.io.FilePermission "${derby.install.path}${/}-", "read"</a>
      </block>

      <block>
        <comment>Gives permission for JMX to be used against Derby
but only if JMX authentication is not being used.
In that case the application would need to create
a whole set of fine-grained permissions to allow specific
users access to MBeans and actions they perform.</comment>
        <a>org.apache.derby.shared.common.security.SystemPermission "engine", "monitor"</a>
        <a>org.apache.derby.shared.common.security.SystemPermission "server", "monitor"</a>
      </block>

    </jar>

  </policy>

  <!-- org.apache.derby.engine -->

  <policy>
    <name>basicEngine</name>
    <include>basicCommons</include>

    <jar>
      <name>derby.jar</name>

      <block>
        <comment>These permissions are needed for everyday, embedded Derby usage.</comment>
        <a>java.lang.RuntimePermission "createClassLoader"</a>
        <a>java.util.PropertyPermission "derby.*", "read"</a>
        <a>java.util.PropertyPermission "user.dir", "read"</a>
        <a>org.apache.derby.shared.common.security.SystemPermission "engine", "usederbyinternals"</a>
        <a>java.io.FilePermission "${derby.system.home}","read,write"</a>
        <a>java.io.FilePermission "${derby.system.home}${/}-", "read,write,delete"</a>
        <a>java.io.FilePermission "${derby.system.home}${/}derby.properties", "read"</a>
        <a>java.io.FilePermission "${derby.system.home}${/}derby.log", "read,write,delete"</a>
      </block>

      <block>
        <comment>Properties needed to determine if the VM is 32 or 64 bit.</comment>
        <a>java.util.PropertyPermission "sun.arch.data.model", "read"</a>
        <a>java.util.PropertyPermission "os.arch", "read"</a>
      </block>

      <block>
        <comment>Gives permission for JMX to be used against Derby
but only if JMX authentication is not being used.
In that case the application would need to create
a whole set of fine-grained permissions to allow specific
users access to MBeans and actions they perform.</comment>
        <a>org.apache.derby.shared.common.security.SystemPermission "jmx", "control"</a>
        <a>org.apache.derby.shared.common.security.SystemPermission "engine", "monitor"</a>
        <a>org.apache.derby.shared.common.security.SystemPermission "server", "monitor"</a>
      </block>

      <block>
        <comment>Permissions needed for JMX based management and monitoring.</comment>
        <a>javax.management.MBeanServerPermission "createMBeanServer"</a>
      </block>

      <block>
        <comment>Allows access to Derby's built-in MBeans, within the domain
org.apache.derby.  Derby must be allowed to register and unregister these
MBeans.  To fine tune this permission, see the javadoc of
javax.management.MBeanPermission or the JMX Instrumentation and Agent Specification.</comment>
       <a>javax.management.MBeanPermission "org.apache.derby.*#[org.apache.derby:*]", "registerMBean,unregisterMBean"</a>
      </block>

      <block>
        <comment>Trusts Derby code to be a source of MBeans and to register these in the MBean server.</comment>
        <a>javax.management.MBeanTrustPermission "register"</a>
      </block>

      <block>
        <comment>Optional permission needed for printing classpath information to derby.log.</comment>
        <a>java.lang.RuntimePermission "getProtectionDomain"</a>
      </block>

      <block>
        <comment>The following permission must be granted for Connection.abort(Executor) to work.
Note that this permission must also be granted to outer (application) code domains.</comment>
        <a>java.sql.SQLPermission "callAbort"</a>
      </block>

      <block>
        <comment>Needed by FileUtil#limitAccessToOwner.</comment>
        <a>java.lang.RuntimePermission "accessUserInformation"</a>
        <a>java.lang.RuntimePermission "getFileStoreAttributes"</a>
      </block>

    </jar>

  </policy>

  <!-- optional engine permissions -->

  <policy>
    <name>optionalEngine</name>

    <jar>
      <name>derby.jar</name>

      <block>
        <comment>Needed to create a temp file in order to open a database in a jar file.
permission java.io.FilePermission "${java.io.tmpdir}${/}-", "read,write,delete"</comment>
      </block>

      <block>
        <comment>Customize the following permission in order to backup and restore
Derby databases to/from a secure branch of your file system,
preferably one owned by the database owner or the user who booted the JVM:
permission java.io.FilePermission "/Users/me/backups/-", "read,write"</comment>
      </block>

      <block>
        <comment>Customize the following permission in order to export and import
tables to/from a secure branch of your file system,
preferably one owned by the database owner or the user who booted the JVM:
permission java.io.FilePermission "/Users/me/imports/-", "read,write"</comment>
      </block>

      <block>
        <comment>Customize the following permission in order to load
jar files which contain user-written types, aggregates, functions, and procedures.
Those jar files should live in a secure branch of your file system,
preferably one owned by the database owner or the user who booted the JVM:
permission java.io.FilePermission "/Users/me/myJars/-", "read"</comment>
      </block>

      <block>
        <comment>This permission lets a DBA reload the policy file while the server
is still running. The policy file is reloaded by invoking
the SYSCS_UTIL.SYSCS_RELOAD_SECURITY_POLICY() system procedure:
permission java.security.SecurityPermission "getPolicy"</comment>
      </block>

      <block>
        <comment>This permission is needed to call DriverManager.deregisterDriver()
and unload the Derby classes:
permission java.sql.SQLPermission "deregisterDriver"</comment>
      </block>

    </jar>

  </policy>

  <!-- engine template -->

  <policy>
    <name>engineTemplate</name>
    <include>basicEngine</include>
    <include>optionalEngine</include>
    <output>
      <file>generated/java/org.apache.derby.engine/org/apache/derby/security/engineTemplate.policy</file>
      <properties>securityProduct.properties</properties>
    </output>

    <jar>
      <name>derby.jar</name>

    </jar>

  </policy>

  <!-- org.apache.derby.tools -->

  <policy>
    <name>basicTools</name>
    <include>basicEngine</include>
    <output>
      <file>generated/java/org.apache.derby.engine/org/apache/derby/security/toolsTemplate.policy</file>
      <properties>securityProduct.properties</properties>
    </output>

    <jar>
      <name>derbytools.jar</name>

      <block>
        <comment>Access all properties using System.getProperties -
ij enumerates the properties in order to open connections
for any property set in ij.connection.* and set protocols
for any property in ij.protocol.*</comment>
        <a>java.util.PropertyPermission "*", "read,write"</a>
      </block>

      <block>
        <comment>Needed by sysinfo. The file permission is needed to check the existence
of jars on the classpath. You can limit this permission to just the locations
which hold your jar files.</comment>
        <a>java.util.PropertyPermission "user.*", "read"</a>
        <a>java.util.PropertyPermission "java.home", "read"</a>
        <a>java.util.PropertyPermission "java.class.path", "read"</a>
        <a>java.util.PropertyPermission "java.runtime.version", "read"</a>
        <a>java.util.PropertyPermission "java.fullversion", "read"</a>
        <a>java.lang.RuntimePermission "getProtectionDomain"</a>
        <a>org.apache.derby.shared.common.security.SystemPermission "engine", "usederbyinternals"</a>
        <a>java.io.FilePermission "&lt;&lt;ALL FILES&gt;&gt;", "read"</a>
      </block>

    </jar>

  </policy>

  <!-- core server permissions -->

  <policy>
    <name>coreServer</name>
    <include>basicTools</include>

    <jar>
      <name>derbynet.jar</name>

      <block>
        <comment>Needed by FileUtil#limitAccessToOwner.</comment>
        <a>java.lang.RuntimePermission "accessUserInformation"</a>
        <a>java.lang.RuntimePermission "getFileStoreAttributes"</a>
        <a>java.util.PropertyPermission "derby.__serverStartedFromCmdLine", "read,write"</a>
      </block>

      <block>
